### ISSUE TITLE
Homebridge not updating current state

### ISSUE THREAD

**Issue by Ogge66** [AtomBaf/homebridge-mqtt-tasmota#5]
First of all, thank you for a great plugin. Very easy to add all of my devices, naming, index etc.

But something I haven’t figured out is how to sync the device statuses. Lets say I use the wall switch or have a timer set up in the tasmota web interface then it wont change the status in HomeKit. I can see in the logs that MQTT is sending from the tasmota device but nothing is received in homebridge.

Is this a known bug/limitation or am I just missing something obvious?

Thank you!

**Comment by AtomBaf** [comment]
Thanks for your feedback.
As you're clearly pointing out, this is a more like a limitation I haven't figure out. You can see for instance (here)[https://github.com/AtomBaf/homebridge-mqtt-tasmota/blob/master/src/switch.js#L19] that an assumption is made on the initial state of the system when the first connection is made.

However, I don't have in my own setup the typical thing you're describing: a timer. What exactly tasmota is publishing when a timer-based event is triggered ? If you can send the mqtt message log, I would modify the code to handle this message as well. It seems easy to applicate. I can do it on my own, but not sure if it would help if you have a different version/setup/device on your own tasmota.

Thx again for your help in understanding these things.

**Comment by AtomBaf** [comment]
FYI, I tested some timer on my own setup and the state of the tasmota switch is correctly reflected in homebridge/homekit after a timer event. Did I miss something about your query?

**Comment by Ogge66** [comment]
Hi,

Thank you for the quick reply, much appreciated!
The main issue is that it doesn’t update when I use the physical wall switch. The timers I can just program in the home-app instead of in the tasmota web-interface

In the Homebridge-log it doesn't detect my action when I press the button which I can see in the Tasmota-console. Here I press off in the home-app and then I use the wall switch button (Sonoff T1 touch) to turn the lights back on. But in Homebridge it doesn't detect that action.

Homebridge log:
[1/9/2022, 6:57:35 PM] [Tvättstugan Belysning korridor] Set Power: false
[1/9/2022, 6:57:35 PM] [Tvättstugan Belysning korridor] Updated CurrentPower: OFF

Tasmota console log:
18:57:35 MQT: stat/tasmota_FF740F/RESULT = {"POWER":"OFF"}
18:57:35 MQT: stat/tasmota_FF740F/POWER = OFF
18:57:46 MQT: stat/tasmota_FF740F/RESULT = {"POWER":"ON"}
18:57:46 MQT: stat/tasmota_FF740F/POWER = ON

I need to log on to my Synology to find the logs for the timers I had earlier today to verify that it's acting the same or if I'm misstaken.

Thank you!

Please let me know if I can contribute to your support in any way.

**Comment by AtomBaf** [comment]
I maybe won't be very helpful, but as far as I can see, the code is explicitly listening to the `stat/XXX/RESULT` topic.
https://github.com/AtomBaf/homebridge-mqtt-tasmota/blob/e9de22c821d8d351873862d72896e6d41729cb94/src/switch.js#L13
Any message from this topic is then handled and parsed to update the state of the accessory. https://github.com/AtomBaf/homebridge-mqtt-tasmota/blob/e9de22c821d8d351873862d72896e6d41729cb94/src/switch.js#L46

Maybe one hint: do you have in your accessory definition an `index` set? As you can see in the code, if this is true, then the parsing function will expect `POWER1` instead of `POWER` to be published in the mqtt message by the tasmota device. I did some trials on effectively tasmota is publishing a `POWER` message and not `POWER1` if the device is a simple switch. This could be the cause of your problem which I would solve easily. 

Let me know your config, and if you can grap it, all the MQTT messages published during your test case.

**Comment by AtomBaf** [comment]
Finally got it and fixed it. 
Thx for your patience and feedback.

**Comment by Ogge66** [comment]
Hi

Wow, that was quick!
And with this update all devices status are also synced when Homebridge is restarted! Thank you so much!

**Comment by Ogge66** [comment]
And how can I Donate a contribution for this?

Best regards
Oscar

**Comment by AtomBaf** [comment]
Thx Oscar, this is not necessary to donate, but if you'd like to, this is much appreciated.
Updated to version 0.4.6

**Comment by Ogge66** [comment]
Hi Fabien

Well you saved me a lot of hazzle and headache so I sent you 10 Euros anyway.

Thank you very much!

Best regards
Oscar
